apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:   
      containers:
        - image: chzbrgr71/loadtest:v3.1
          name: loadtest
          env:
            - name: LOAD_DURATION
              value: "-1"
            - name: LOAD_RATE
              value: "2"
            - name: URL
              value: http://52.154.63.0:3012/latest